### ISSUE TITLE
search regex requirements

### ISSUE THREAD

**Issue by brenna** [tedconf/ember-searchable-select#1]
First draft:
* default to simple string match on word boundary of label
* boolean flag to match on entire string (not just word boundary)
* some more robust way to specify your own completely custom regex

**Comment by samselikoff** [comment]
based on our discussion something like this would be nice:

```js
// the context that's rendering ted-select
export default Component.extend({

  people: Ember.computed.alias('model'),

  actions: {
    searchFilter(item, q) {
      return item.get('text').match(q)[0].length > -1;
    }
  }

});
```

```hbs
{{ted-select items=people
  filteringFunction=(action 'searchFilter')}}

```

This lets the caller specify a more complicated filtering function

**Comment by brenna** [comment]
ah right, that makes a lot of sense since I was planning on sending out some an on-search action anyhow.

**Comment by ryanto** [comment]
This would be nice too. 

```
{{ted-searchable-select list=myList on-text-change=(action "mutateMyList")}}
```

I get an action when the text changes so I can change the items in the list (use case is ajax auto completing).

**Comment by brenna** [comment]
@ryanto @samselikoff i like the idea of passing off custom regex handling to the consumer through an `on-text-change` action. Like Ryan said, this same action could handle AJAX populating a list as well.  Follow up q on that, should passing in an `on-text-change` action automatically disable the internal filter, or is that an alternate configurable option (`disableFilter=false` or something). 

I think i prefer the former because it's less error prone for users - I thought my external regex was busted for a long time, but it was the internal filter exclusing my custom results, but wondering if there's any cases where you'd want both that action *and* the internal filter?

**Comment by brenna** [comment]
We've landed on:

* default to simple string search filter
* optional `limitToWordBoundary` option to limit search to beginning of words
* optional `on-search` action will disable internal filtering, assuming user is handling filtering outside component

```
{{ted-searchable-select content=myList on-search=(action "updateContentList")}}

**Comment by brenna** [comment]
closing for now. we can re-open if other use cases arise.
