### ISSUE TITLE
infinity scroll, paging

### ISSUE THREAD

**Issue by acerov** [tedconf/ember-searchable-select#27]
Hi,
I am deciding which select component to use, tried select-2, ember-power-select.
I will try to explain what I would like to achieve through example.
You have 1 million items on server, using asynchronous search you hit server with search "term" that qualifies 1000 items but server pages response in chunks of 25 and as you scroll down the options it gets page by page in infinite scrolling mode.
I am not sure how to implement it but maybe some action that fires when you scrolled to the end of options will help, so we can ajax for new page of results.

**Comment by brenna** [comment]
Hi @acerov,

To implement fully, this requires a lot of list state awareness inside the component, which I don't think belongs in the core API atm.

Your best bet would be to 1) work with a throttled results set or 2) extend and customize the component for your own use. 

Feasibility of #1 would depend on your data set, but perhaps you could limit your results to something like the first 50, then rely on the user typing more to refine the list further and get a manageable set?

For #2, here's an explanation of [how to extend an addon in your own app](http://stackoverflow.com/a/31364714/1554938). If you wanted to customize the template to include features like a loading indicator, you would add your own `searchable-select.hbs` to your project and base it on [the addon default](https://github.com/tedconf/ember-searchable-select/blob/master/addon/templates/components/searchable-select.hbs). 

Hope that helps! If you get a nice extension working for this use case, let me know and perhaps we can add it to the docs site as an example.

**Comment by acerov** [comment]
Hi @brenna ,

thank you for suggestions, I went with 1) for now, just limiting to first x records

**Comment by heygrady** [comment]
@acerov I needed something similar for a project. You might like to check out [this gist](https://gist.github.com/heygrady/fc6a34e236bcce2a2e09). It follow's @brenna's suggestion of extending the searchable select component. I would suggest creating a new component called "searchable-select-infinite" in your project. This solution was tested against version 0.6.3 and has worked great for my needs.

Adds a few UI elements and a new action for triggering the addition of new items once you've scrolled to the bottom.

You'd use it like this (presuming you created a new component called `searchable-select-infinite` using the code in the gist mentioned above):

```hbs
{{searchable-select-infinite
  content=results
  meta=meta
  selected=selected
  isLoading=isLoading
  isLoadingMore=isLoadingMore
  on-change=(action "change")
  on-search=(action "search")
  on-search-more=(action "searchMore")}}
```

The difference from the vanilla searchable-select is the addition of `meta`, `isLoadingMore` and `on-search-more`.

You can also prevent automatically loading additional pages using `autoloadMore=false`. If you don't autoload results there will be a button added to the results list for requesting more results.

The `meta` object should work with Ember Data without any modification. If your results are paginated your backend should be returning a meta object already. If not, you can easily create your own. It expects an object that looks like this: `{total: 100, page: 1, pages: 10, per_page: 10}`. Specifically the extended `searchable-select-infinity` component looks for the `total`, `page`, and `pages` in the passed `meta` object for deciding when/if to load additional pages.

Your component would look like this (presuming you're using ember-cli and using Ember Data to search for results):

```js
import Ember from 'ember';

export default Ember.Component.extend({
  store: Ember.inject.service('store'),

  results: null,
  meta: null,
  selected: null,
  isLoading: false,
  isLoadingMore: false,

  actions: {
    change(selected) {
      this.set('selected', selected);
    },

    search(text, page = 1) {
      // reset search on empty text
      if (!text.trim()) {
        this.set('isLoading', false);
        this.set('isLoadingMore', false);
        this.set('results', null);
        this.set('meta', null);
        return;
      }

      // set the loading indicator
      this.set('isLoading', true);

      // search for something on the store
      // presume backend allows for searching my-things by name
      // presume that it takes a "page" parameter for requesting a specific page
      // presume it returns a "meta" with the results
      this.get('store').query('my-thing', {name: text, page}).then(results => {
        if (this.get('isLoadingMore')) {
          // prepend the previous results
          const previousResults = this.get('results');
          this.set('results', results.toArray().unshiftObjects(previousResults));
        } else {
          this.set('results', results.toArray());
        }

        // meta should include keys for "total", "page" and "pages"
        this.set('meta', results.get('meta'));

        // done loading
        this.set('isLoading', false);
        this.set('isLoadingMore', false);
      });
    },

    searchMore(text, nextPage) {
      // "loading more" lets the search know to add
      // the new results to the previous results
      // instead of replacing the previous results
      this.set('isLoadingMore', true);

      // the searchable-select-inifinite component will
      // increment the "page" value from the "meta" object
      this.send('search', text, nextPage);
    }
  }
});
```
