### ISSUE TITLE
MutliSelect with TwoWayBound?

### ISSUE THREAD

**Issue by imartinezingsw** [tedconf/ember-searchable-select#37]
Is there a way to pre load selected items? TwoWaBound shows a way to only load one item, but what if I have a list of already selected items? I'm trying to load an array but I'm getting this error:

`Uncaught Error: Searchable select: passed in multiple selection must be an array`

**Comment by brenna** [comment]
Can you provide an [Ember twiddle](https://ember-twiddle.com/) with your code that's producing this error so I can debug?

**Comment by imartinezingsw** [comment]
Thank you for the quick response. But actually it was something that I was doing wrong. It's working perfectly.
