### ISSUE TITLE
Accessing property on onchange value

### ISSUE THREAD

**Issue by aamir-pk** [tedconf/ember-searchable-select#51]
Hi,

I am trying to get the id of selected element but unable to do it so far. I tried multiple options but nothing worked. Is there any bug or I am missing something. This is the code:

```
      {{ted-select  content=operators
                    onchange=(action (mut condition.operator) (get value key) )
                    optionValueKey="key"
                    optionLabelKey="name"
                    selectClassNames="form-control"
                    selectId="listOp"
                    prompt=null
      }}

```

**Comment by brenna** [comment]
Hi @aamir-pk,

It looks like you're using `ember-ted-select`(https://github.com/tedconf/ember-ted-select), in your snippet, not this addon (`ember-searchable-select`). If it's an issue with `ember-ted-select`, please file in that repo.

**Comment by aamir-pk** [comment]
Very sorry I posted it in hurry. Really embarrassing for me.

**Comment by brenna** [comment]
Moved to https://github.com/tedconf/ember-ted-select/issues/34

**Comment by brenna** [comment]
@romulomachado i don't have permission to close this issue, can you?
