### ISSUE TITLE
Call clear function programmatically

### ISSUE THREAD

**Issue by EVolpert** [tedconf/ember-searchable-select#53]
Is there a way to call the function clear(), the same that is used on the clear button programmatically? I'm using 3 searchable-selects in a hierarchy of university > campus > club and when I clean the highest level I wanted to clear the other two bellow, however I did not see a way of calling this function in the on-change action.

**Comment by brenna** [comment]
@EVolpert The best way to do that would be to set the value of the child selects to `null` when the parent select is cleared. Clearing the parent select should trigger an `on-change` with a `null` value that you can check for and then send down `null` data for your child selects.

**Comment by EVolpert** [comment]
Thanks @brenna worked perfectly.
